//! Autogenerated weights for pallet_escrow
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `benchmark`, CPU: `Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/substrate
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_escrow
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=pallets/escrow/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame::prelude::*;
use frame::runtime::prelude::weights::constants::RocksDbWeight;
use core::marker::PhantomData;

/// Weight functions needed for pallet_escrow.
pub trait WeightInfo {
    fn create_escrow() -> Weight;
    fn release_escrow() -> Weight;
    fn refund_escrow() -> Weight;
    fn reclaim_escrow() -> Weight;
    fn set_fee() -> Weight;
}

/// Weights for pallet_escrow using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame::deps::frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: Escrow NextEscrowId (r:1 w:1)
    /// Storage: Escrow ActiveByUser (r:1 w:1)
    /// Storage: Balances Account (r:2 w:2)
    /// Storage: Escrow Escrows (r:0 w:1)
    fn create_escrow() -> Weight {
        Weight::from_parts(45_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(5))
    }
    
    /// Storage: Escrow Escrows (r:1 w:1)
    /// Storage: Escrow PlatformFee (r:1 w:0)
    /// Storage: Balances Account (r:2 w:2)
    /// Storage: Escrow ActiveByUser (r:1 w:1)
    fn release_escrow() -> Weight {
        Weight::from_parts(40_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(4))
    }
    
    /// Storage: Escrow Escrows (r:1 w:1)
    /// Storage: Balances Account (r:2 w:2)
    /// Storage: Escrow ActiveByUser (r:1 w:1)
    fn refund_escrow() -> Weight {
        Weight::from_parts(38_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(4))
    }
    
    /// Storage: Escrow Escrows (r:1 w:1)
    /// Storage: System BlockNumber (r:1 w:0)
    /// Storage: Balances Account (r:2 w:2)
    /// Storage: Escrow ActiveByUser (r:1 w:1)
    fn reclaim_escrow() -> Weight {
        Weight::from_parts(39_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(4))
    }
    
    /// Storage: Escrow PlatformFee (r:1 w:1)
    fn set_fee() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn create_escrow() -> Weight {
        Weight::from_parts(45_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(5))
    }
    
    fn release_escrow() -> Weight {
        Weight::from_parts(40_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    
    fn refund_escrow() -> Weight {
        Weight::from_parts(38_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    
    fn reclaim_escrow() -> Weight {
        Weight::from_parts(39_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(4))
    }
    
    fn set_fee() -> Weight {
        Weight::from_parts(15_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
    }
}